[package]
name = "canduma"
version = "0.1.0"
authors = ["Julien Lenne <julien.lenne@cocolabs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8"
actix-web = {version = "1.0", features = ["ssl"]}
actix-identity = "*"
openssl = { version = "0.10", features = ["v110"] }
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.4.2", features = ["postgres", "uuidv07", "chrono", "r2d2"] }
dotenv = "0.9.0"
env_logger = "0.6"
futures = "0.1"
juniper = { git = "https://github.com/graphql-rust/juniper.git"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
rand = "*"
argon2rs = "*"
derive_more = "*"
jsonwebtoken = "6"
actix-web-httpauth = "0.3.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3